//导入字体
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",/*是给字体在 CSS 中起了一个可引用的名字（CSS 变量）*/
  subsets: ["latin"],/*加载Geist 但只加载latin字体 减小文件大小*/ 
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
/*Next.js框架中
只有page.js 或者layout.js中的export const metadata会自动生效
起到定义网站标题与描述的名片作用*/

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
